/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p5servidorutc;

import java.rmi.RemoteException;
import static p5servidorutc.UTC.obtenerUTC;
import reloj.Relojes;

/**
 *
 * @author jSeba
 */
public class FrameServidor extends javax.swing.JFrame implements Runnable{

    P5ServidorUTC serverUTC;
    public Relojes reloj;
    public Thread h1,h2;
    public String[] horaUTC;
    public int timer1=1000;
    public boolean registroServers=false;
    public FrameServidor() throws RemoteException{
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Servidor UTC");
        setVisible(true);
        serverUTC = new P5ServidorUTC();
        serverUTC.iniciarServidor();
        reloj = new Relojes();
        h1 = new Thread(this);
        h1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Servidor UTC");

        lblReloj.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("lblReloj");

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblReloj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        //manda las actualizaciones
        try {
            serverUTC.server1.sincronizarServidor();
            serverUTC.server2.sincronizarServidor();
            System.out.println("Mande Sincronizacion");
        } catch (Exception e) {
            System.out.println("No pude sincronizarServidor en server UTC: "+e);
        }
    }//GEN-LAST:event_ActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        
        
        while(ct==h1)
        {
            if(serverUTC.server1==null)
                System.out.println("referencia a server 1 es null");
            
            if(serverUTC.server2==null)
                System.out.println("referencia a server 2 es null");
            
            if(reloj.aux==0)
            {
                horaUTC=obtenerUTC().split(":");
                reloj.aux=1;
                reloj.hora=horaUTC[0];
                reloj.minutos=horaUTC[1];
                reloj.segundos=horaUTC[2];
            }else
            {
                reloj.actualiza();
            }
            lblReloj.setText(" ");
            lblReloj.setText(reloj.hora+":"+reloj.minutos+":"+reloj.segundos);
            
            try{
            Thread.sleep(timer1);
            }catch(Exception e)
            {
                System.out.println("No pudo esperar: "+e);
            }
        }
    }
}
