/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Psychedelic
 */

import java.io.DataInputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Calendar;


public class MinutoFrame extends javax.swing.JFrame implements Runnable{
    Calendar calendario;
    Thread minutoHiloC1;
    Relojes minutoC1;
    int timer1 = 1000;
    String str;
    int valorRecibido=-2;
    int actual=0;
    
    SockerEscucha SocketReceive=null;

    /**
     * Creates new form MinutoFrame
     */
    public MinutoFrame() {
        minutoC1=new Relojes();
        initComponents();
        
        minutoHiloC1 = new Thread(this); //inicializando cada hilo       
        minutoHiloC1.start();
        
        SocketReceive = new SockerEscucha();
        SocketReceive.start();
        
        
    }
     @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == minutoHiloC1) //mientras el hilo se este ejecutando
        {
            if (minutoC1.aux != 1) //si aun no entra por primera vez
            {
                minutoC1.calcula();       
            }
            if(valorRecibido==-2)
            {
               
            LabelHora.setText(minutoC1.minutos);
            minutoC1.actualiza();
            }
            else
            {
                LabelHora.setText(minutoC1.minutos);
                minutoC1.actualiza2(actual);
                actual=Integer.parseInt(minutoC1.minutos);
            }
            System.out.println("segunderoMin: "+minutoC1.segundos);
            try {
                Thread.sleep(timer1);
            } catch (InterruptedException e) {
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelHora.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        LabelHora.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setText("Minutos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(LabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(LabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinutoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinutoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

public class SockerEscucha extends Thread {
    ServerSocket serverSocket;
    Socket socketC1;
    public SockerEscucha(){
        try {  
            serverSocket=new ServerSocket(6678);
            System.out.println("Serversocket creado en puerto 6678 para minuto");
        } catch (IOException ex) {
            System.out.println("Error creando Serversocket en puerto 6679 para minuto");
        }
    }
    @Override
    public void run() {
                try{  
                while(true){
                    socketC1=serverSocket.accept();//establishes connection   
                    DataInputStream dis=new DataInputStream(socketC1.getInputStream());  
                    str=(String)dis.readUTF();  

                    minutoHiloC1.suspend();
                    String[] parts=str.split(":");
                    actual=Integer.parseInt(parts[1]);
                    if(parts[1]!=null)
                    {
                        valorRecibido++;
                        minutoC1.hora=(String)parts[0];
                        minutoC1.minutos=(String)parts[1];
                        minutoC1.segundos=(String)parts[2];
                    }
                        LabelHora.setText(parts[1]);
                    
                    minutoHiloC1.resume();
                    System.out.println("parts: "+parts);
                    socketC1.close(); 
                }
                }catch(Exception e){System.out.println("Error al recibir el dato minuto"+e);}  
            }
    }

}

