/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidorrmi_j2;

import BD.Cls_Servidor;
import Reloj.Modifica;
import Reloj.Relojes;
import interfazp7.InterfaceServidores;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jSeba
 */
public class ServidorFormS2 extends javax.swing.JFrame implements Runnable{

    ServidorRMI_2 server;
    public Thread h1,h2,h3;
    public DisplayImage IMAGEN;
    public Cls_Servidor BD;
    public Modifica m;
    public Relojes reloj; 
    public int partidaNueva = 0;
    public Calendar calendario;
    public String fecha,hora_inicio,hora_fin;
    public int timer1=1000;
    public String serverHora;
    public boolean ejecuteUpdate=false;
    int activaHilos=0;//activara los hilos hasta que detecte que el servidor 2 ya esta conectado y se pueden hacer procedimientos remotos
    //datos para server 1
    public String server1Address = "localhost";//ip del servidor 1
    public int server1Port = 3000;//puerto del server 1
    public String QueryActual;
    public int reinicio=0;
    public boolean activaHilo=false;
    
    public ServidorFormS2() throws RemoteException {
        initComponents();
        server = new ServidorRMI_2();
        server.iniciarServidor();
        IMAGEN = new DisplayImage();
        BD = new Cls_Servidor();
        reloj = new Relojes();
        h1 = new Thread(this);
        h2 = new Thread(this);
        h3 = new Thread(this);
        h1.start();
        h2.start();
        h3.start();
        this.setLocationRelativeTo(null);
        this.setTitle("Servidor 2");
        this.setVisible(true);
        
        //OBTENIENDO LA REFERENCIA DEL SERVER 1
        
        try {
            Registry registry = LocateRegistry.getRegistry(server1Address, server1Port); //obtiene el registro de la maquina con la ip seleccionada
            server.servidor1Obj = (InterfaceServidores)(registry.lookup("server1"));//localiza lo guardado en el registro con la palabra "operacionservidor"
            server.servidor1Obj.agregaServer2(server);//agregamos el server2 a la referencia del server 1
        } catch (NotBoundException ex) {
            System.out.println("No se pudo obtener la referencia del servidor 1 en servidor 2");
        } 
        
        //OBTENIENDO LA REFERENCIA DEL SERVER 1
        
        try {
            ImageIcon icon = IMAGEN.DisplayImage("0");//pone el inverso de la carta
            imagenCarta.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(ServidorFormS2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        imagenCarta = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Reiniciar = new javax.swing.JButton();
        lblLamport = new javax.swing.JLabel();
        ReiniciarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Servidor 2");

        lblReloj.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Reiniciar.setText("Reiniciar");
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });

        lblLamport.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblLamport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLamport.setText("lblLamport");

        ReiniciarC.setText("Reiniciar contador");
        ReiniciarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLamport, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ReiniciarC)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Reiniciar)
                        .addGap(53, 53, 53))))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagenCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reiniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Modificar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLamport, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ReiniciarC)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        server.cartas = server.llenarLista(server.cartas);//llena la lista de donde se sacan las claves de las cartas
        partidaNueva = 0;
        reinicio=1;
        ejecuteUpdate=false;
        try {
            ImageIcon icon = IMAGEN.DisplayImage("0");//pone el inverso de la carta
            imagenCarta.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(ServidorFormS2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReiniciarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        h1.suspend();
        Modifica m = new Modifica();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        m.setTitle("Modificar Reloj 2");
        m.invocador=1;
        m.relojOriginal=this;
    }//GEN-LAST:event_ModificarActionPerformed

    private void ReiniciarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarCActionPerformed
        server.cLamport=0;
    }//GEN-LAST:event_ReiniciarCActionPerformed

    //=====================================================================================================================
    //=====================================================================================================================
    //=====================================================================================================================
    public void QueryServer1()
    {
        try
        {
            server.servidor1Obj.queryRemoto(QueryActual);//Hace el query remoto para el server 1;
            server.servidor1Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException e)
        {
            System.out.println("Excepcion haciendo consultas a server 1 :"+e);
        }
    }
    
    public void QueryServer3()
    {
        try
        {
            server.servidor3Obj.queryRemoto(QueryActual);//Hace el query remoto para el server 1;
            server.servidor3Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException e)
        {
            System.out.println("Excepcion haciendo consultas a server 3 :"+e);
        }
    }
    
    public void eliminaCartaS1(String clave)
    {
        try
        {
            server.servidor1Obj.eliminaCartaRemota(clave);
            server.servidor1Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException e)
        {
            System.out.println("Excepcion eliminando cartas en server 1 :"+e);
        }
    }
    
    public void eliminaCartaS3(String clave)
    {
        try
        {
            server.servidor3Obj.eliminaCartaRemota(clave);
            server.servidor3Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException e)
        {
            System.out.println("Excepcion eliminando cartas en server 3 :"+e);
        }
    }
    
        public void jugandoPartidaS1(String horai, String fecha)
    {
        try
        {
            server.servidor1Obj.jugandoPartida(horai, fecha);//avisa que esta jugando una partida
            server.servidor1Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException e)
        {
            System.out.println("Excepcion eliminando cartas en server 3 :"+e);
        }
    }
    
    public void jugandoPartidaS3(String horai, String fecha)
    {
        try
        {
            server.servidor3Obj.jugandoPartida(horai, fecha);
            server.servidor3Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException e)
        {
            System.out.println("Excepcion eliminando cartas en server 3 :"+e);
        }
    }
    
    //=====================================================================================================================
    //=====================================================================================================================
    //=====================================================================================================================
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JButton ReiniciarC;
    private javax.swing.JLabel imagenCarta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLamport;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = new Thread();
        ct = Thread.currentThread();//obtiene el hilo ejecutado en ese momento
        
        while(ct==h1)//hilo para la actualizacion del reloj
        {
            try{
                //System.out.println("reloj.aux = "+reloj.aux);
                if (reloj.aux != 1) //si aun no entra por primera vez
                {
                    reloj.generaHora();
                    //System.out.println("Acabo de ejecutar r1.calcula()");
                    //System.out.println("hilo: "+h1.getName()+"Entre a calcular, auxiliar:"+r1.aux);
                }
                //System.out.println("reloj.aux = "+reloj.aux+" : "+reloj.hora +":"+ reloj.minutos +":"+ reloj.segundos);
                lblReloj.setText(reloj.hora +":"+ reloj.minutos +":"+ reloj.segundos);//pone la hora en el label
                serverHora = lblReloj.getText();
                reloj.actualiza();
                
                lblLamport.setText("");
                lblLamport.setText("Contador: "+Integer.toString(server.cLamport));//pone el valor del contador en el label
                server.cLamport+=1;//cada segundo aumenta el contador de lamport
                //System.out.println("Server primario = "+ server.primario);
                
            }catch(Exception e){System.out.println("Error al generar hora"+e);}    
                
                try {
                        Thread.sleep(timer1);
                    } catch (InterruptedException e) {
                        System.out.println("Error al esperar"+e);
                    }
                    
        }
        
        //System.out.println("primario="+server.primario);
        while(ct==h2)//hilo para las peticiones del cliente
        {
            System.out.println("Server.peticion = "+ server.peticion);
            if(server.primario==true)
            {    
                if(partidaNueva == 0 && activaHilos==1 && server.jugandoPartida==false)
                {
                    partidaNueva=1;
                    server.jugandoPartida = true;
                    fecha = server.getFecha();//pone el mes/dia/año
                    server.fecha = server.getFecha();
                    hora_inicio = serverHora;
                    server.hora_Inicio = hora_inicio; //guarda su hora inicio en server
                    jugandoPartidaS1(hora_inicio, fecha);//avisa que hay una partida en juego y se manda la hora inicio del servidor que pudo se enviada remotamente
                    jugandoPartidaS3(hora_inicio, fecha);
                    try 
                    {
                    System.out.println("fecha: "+fecha+" hora: "+hora_inicio);
                    QueryActual=BD.insertPartida(fecha, hora_inicio);
                    }catch (SQLException ex){System.out.println("No se pudo hacer insertPartida");}
                    QueryServer1();
                    QueryServer3();
                }

                if(server.peticion==true && activaHilos==1)//Revisa si hay una nueva peticion
                {
                    server.peticion = false;//como se acepta la peticion no se reciben en este momento
                    String nombreCarta = server.cartaActual;//obtiene la carta entregada al usuario
                    String clave = server.clave;//obtiene la clave de esa carta actual
                    if(!nombreCarta.equals(" "))//sino recibe cadena vacía
                    {    
                        System.out.println("nombreCarta: "+nombreCarta+" Clave: "+clave);
                        try {
                            //BUSCA LA IMAGEN Y LA PONE EN LABEL
                            ImageIcon icon = IMAGEN.DisplayImage(clave);//se busca la imagen en la carpeta con el nombre "clave" correspondiente
                            imagenCarta.setIcon(icon);//pone la imagen en el label
                            //HACE EL INSERT EN LA TABLA DE PETICIONES
                            QueryActual=BD.insertPeticion(clave, server.ipJugadorActual, server.valorCartaActual,serverHora,2); //inserta la peticion en la bd
                            }catch (IOException ex)
                            {
                                System.out.println("Error: "+ex);
                                JOptionPane.showMessageDialog(null,"No se encontro la imagen"); 
                            }catch (SQLException ex) 
                            {
                                System.out.println("No se pudo hacer el insertPeticion");
                            }
                            //HACE LAS CONSULTAS REMOTAS PREGUNTANDO PRIMERO SI SON VALIDAS LAS REFERENCIAS
                            QueryServer1();
                            QueryServer3();
                            //HACE LAS CONSULTAS REMOTAS PREGUNTANDO PRIMERO SI SON VALIDAS LAS REFERENCIAS
                            if(reinicio==0)//si aun no se reinicia por primera vez
                            {
                                eliminaCartaS1(clave);//elimina la carta por cada server
                                eliminaCartaS3(clave);
                            }    
                    }else
                    {
                        JOptionPane.showMessageDialog(null,"Ingresa nombre de la cadena"); 
                    }    
                }

                //System.out.println("isEmpty="+server.cartas.isEmpty()+" update:"+ejecuteUpdate+" server.primario="+server.primario);
                if(server.cartas.isEmpty()==true && ejecuteUpdate==false)//si ya no hay más elementos en la lista la partida termino
                {
                    hora_fin = serverHora;//llamada a funcion que retorna la hora actual
                    try
                    {
                        System.out.println("Haciendo updatePartida en S2");
                        QueryActual=BD.updatePartida(hora_fin, server.hora_Inicio, server.fecha);//se manda la hora inicio del servidor que pudo se enviada remotamente para encontrar la hora de inicio correcta de la partida
                        System.out.println("QueryActual = "+QueryActual);
                    }catch(SQLException ex)
                    {
                        System.out.println("No se pudo hacer el updatePartida");
                    }
                    QueryServer1();
                    QueryServer3();
                    ejecuteUpdate=true;   
                }

                try {
                    Thread.sleep(500);
                } catch (Exception e) {
                    System.out.println("no pudo esperar 500 milisegundos en h2: "+e);
                }
            }    
        }
        
        while(ct==h3)//hilo para permitir el aviso de que se tiene referencia al servidor 2 y 3
        {
            System.out.println("activaHilos="+activaHilos);
            if(!(server.servidor3Obj == null))//Si ya hay referencia no nula al servidor 2 y 3
            {
                activaHilos=1;//permite a los otros hilos correr
                h3.stop();//elimina el hilo
            }
        }
    }
}
