/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidorrmi_j2;

import BD.Cls_Servidor;
import Reloj.Modifica;
import Reloj.Relojes;
import interfazp8.InterfaceServidores;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jSeba
 */
public class ServidorFormS2 extends javax.swing.JFrame implements Runnable{

    ServidorRMI_3 server;
    public Thread h1,h2,h3,h4;
    public DisplayImage IMAGEN;
    public Cls_Servidor BD;
    public Modifica m;
    public Relojes reloj; 
    public int partidaNueva = 0;
    public Calendar calendario;
    public String fecha,hora_inicio,hora_fin;
    public int timer1=1000;
    public String serverHora;
    public boolean ejecuteUpdate=false;
    public int i=0;
    public String server3Address = "localhost";//ip del servidor 1
    public int server3Port = 5000;//puerto del server 1
    //datos para server 1
    public String server1Address = "localhost";//ip del servidor 1
    public int server1Port = 3000;//puerto del server 1
    public String QueryActual;//guardara el query que se debe ejecutar en el resto de servidores
    public int reinicio=0;//indica el reinicio en la partida
    //datos para server 1
    //datos para server 2
    public String server2Address = "localhost";//ip del servidor 2
    public int server2Port = 4000;//puerto del server 2
    //datos para server 2
    public int bool = 0;
    
    public ServidorFormS2() throws RemoteException {
        initComponents();
        server = new ServidorRMI_3();
        server.iniciarServidor();
        IMAGEN = new DisplayImage();
        BD = new Cls_Servidor();
        reloj = new Relojes();
        h1 = new Thread(this);
        h2 = new Thread(this);
        h3 = new Thread(this);
        h1.start();
        h2.start();
        h3.start();
        this.setLocationRelativeTo(null);
        this.setTitle("Servidor 3");
        this.setVisible(true);
        
        try {
            ImageIcon icon = IMAGEN.DisplayImage("0");//pone el inverso de la carta
            imagenCarta.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(ServidorFormS2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //OBTENIENDO LA REFERENCIA DEL SERVER 1
        obtenerReferenciaS1();
        //OBTENIENDO LA REFERENCIA DEL SERVER 1
        
        //OBTENIENDO LA REFERENCIA DEL SERVER 3
        obtenerReferenciaS2();
        //OBTENIENDO LA REFERENCIA DEL SERVER 3
        System.err.println("SALIENDO DEL CONSTRUCTOR");
        
    }
    
    public void obtenerReferenciaS1()
    {
        try {
            Registry registry = LocateRegistry.getRegistry(server1Address, server1Port); //obtiene el registro de la maquina con la ip seleccionada
            server.servidor1Obj = (InterfaceServidores)(registry.lookup("server1"));//localiza lo guardado en el registro con la palabra "operacionservidor"
            server.servidor1Obj.agregaServer3(server);//agregamos el server2 a la referencia del server 1
        } catch (NotBoundException | RemoteException ex) {
            System.out.println("No se pudo obtener la referencia del servidor 1 en servidor 2");
            return;
        }
    }
    
    public void obtenerReferenciaS2()
    {
        try {
            Registry registry = LocateRegistry.getRegistry(server2Address, server2Port); //obtiene el registro de la maquina con la ip seleccionada
            server.servidor2Obj = (InterfaceServidores)(registry.lookup("server2"));//localiza lo guardado en el registro con la palabra "operacionservidor"
            server.servidor2Obj.agregaServer3(server);//agregamos el server2 a la referencia del server 1
        } catch (NotBoundException | RemoteException ex) {
            System.out.println("No se pudo obtener la referencia del servidor 2 en servidor 3");
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        imagenCarta = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Reiniciar = new javax.swing.JButton();
        lblLamport = new javax.swing.JLabel();
        ReiniciarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Servidor 3");

        lblReloj.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Reiniciar.setText("Reiniciar");
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });

        lblLamport.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblLamport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLamport.setText("lblLamport");

        ReiniciarC.setText("Reiniciar contador");
        ReiniciarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLamport, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ReiniciarC)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Modificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Reiniciar)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imagenCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagenCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Reiniciar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Modificar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLamport, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ReiniciarC)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        server.cartas = server.llenarLista(server.cartas);//llena la lista de donde se sacan las claves de las cartas
        partidaNueva = 0;
        reinicio=1;
        ejecuteUpdate=false;
        try {
            ImageIcon icon = IMAGEN.DisplayImage("0");//pone el inverso de la carta
            imagenCarta.setIcon(icon);
        } catch (IOException ex) {
            Logger.getLogger(ServidorFormS2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReiniciarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        h1.suspend();
        Modifica m = new Modifica();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        m.setTitle("Modificar Reloj 2");
        m.invocador=1;
        m.relojOriginal=this;
    }//GEN-LAST:event_ModificarActionPerformed

    private void ReiniciarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarCActionPerformed
        server.cLamport=0;
    }//GEN-LAST:event_ReiniciarCActionPerformed

    //=====================================================================================================================
    //=====================================================================================================================
    //=====================================================================================================================
    public void QueryServer1()
    {
        try
        {
            server.servidor1Obj.queryRemoto(QueryActual);//Hace el query remoto para el server 1;
            server.servidor1Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion haciendo consultas a server 1 :"+e);
        }
    }
    
    public void QueryServer2()
    {
        try
        {
            server.servidor2Obj.queryRemoto(QueryActual);//Hace el query remoto para el server 1;
            server.servidor2Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion haciendo consultas a server 3 :"+e);
        }
    }
    
    public void eliminaCartaS1(String clave)
    {
        try
        {
            server.servidor1Obj.eliminaCartaRemota(clave);
            server.servidor1Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion eliminando cartas en server 1 :"+e);
        }
    }
    
    public void eliminaCartaS2(String clave)
    {
        try
        {
            server.servidor2Obj.eliminaCartaRemota(clave);
            server.servidor2Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion eliminando cartas en server 3 :"+e);
        }
    }
    
        public void jugandoPartidaS1(String horai, String fecha)
    {
        try
        {
            server.servidor1Obj.jugandoPartida(horai, fecha);//avisa que esta jugando una partida
            server.servidor1Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion eliminando cartas en server 3 :"+e);
        }
    }
    
    public void jugandoPartidaS2(String horai, String fecha)
    {
        try
        {
            server.servidor2Obj.jugandoPartida(horai, fecha);
            server.servidor2Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion eliminando cartas en server 3 :"+e);
        }
    }
    
    public void agregaFES1()
    {
        try
        {
            System.out.println("Agregue FES1");
            server.servidor1Obj.agregaFE_Server(server.FE);//envia su arreglo de FE al otro servidor para que tambien tenga referencia en caso de que el coordinador muera
            server.servidor1Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion agregando FE en S2 :"+e);
        }
    }
    
    public void agregaFES2()
    {
        try
        {
            System.out.println("Agregue FES3");
            server.servidor2Obj.agregaFE_Server(server.FE);//envia su arreglo de FE al otro servidor para que tambien tenga referencia en caso de que el coordinador muera
            server.servidor2Obj.lamport(server.cLamport);//manda su contador de lamport para actualizacion
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion agregando FE en S3 :"+e);
        }
    }
    
    public void actualizaFE(int i)//actualizara los datos del cooordinador en cada FE
    {
        try
        {
            server.FE[i].cambioCoordinador(server3Address, server.PUERTO, server.serverPass);//avisa a los jugadores la direccion del nuevo coordinador
        }catch(RemoteException | NullPointerException e)
        {
            System.out.println("Excepcion actualizando FE:"+i);
        }
    }
    
    //=====================================================================================================================
    //=====================================================================================================================
    //=====================================================================================================================
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JButton ReiniciarC;
    private javax.swing.JLabel imagenCarta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLamport;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = new Thread();
        ct = Thread.currentThread();//obtiene el hilo ejecutado en ese momento
        
        while(ct==h1)//hilo para la actualizacion del reloj
        {
            try{
                //System.out.println("reloj.aux = "+reloj.aux);
                if (reloj.aux != 1) //si aun no entra por primera vez
                {
                    reloj.generaHora();
                    //System.out.println("Acabo de ejecutar r1.calcula()");
                    //System.out.println("hilo: "+h1.getName()+"Entre a calcular, auxiliar:"+r1.aux);
                }
                //System.out.println("reloj.aux = "+reloj.aux+" : "+reloj.hora +":"+ reloj.minutos +":"+ reloj.segundos);
                lblReloj.setText(reloj.hora +":"+ reloj.minutos +":"+ reloj.segundos);//pone la hora en el label
                serverHora = lblReloj.getText();
                reloj.actualiza();
                
                lblLamport.setText("");
                lblLamport.setText("Contador: "+Integer.toString(server.cLamport));//pone el valor del contador en el label
                server.cLamport+=1;//cada segundo aumenta el contador de lamport
                //System.out.println("Server primario = "+ server.primario);
            }catch(Exception e){System.out.println("Error al generar hora"+e);}    
                
                try {
                        Thread.sleep(timer1);
                    } catch (InterruptedException e) {
                        System.out.println("Error al esperar"+e);
                    }
                    
        }
        
        
        while(ct==h2)//hilo para las peticiones del cliente
        {
            if(server.servidor1Obj==null)
                System.out.println("referencia a server 1 es null");
            
            if(server.servidor2Obj==null)
                System.out.println("referencia a server 2 es null");
            
            if(server.primario==true)
            {    
                if(server.FE[0]!=null && bool==0)
                {
                    agregaFES2();
                    agregaFES1();//agrega los Front End a los demas servidores
                    System.out.println("Agregue FE[0]");
                    bool++;
                }

                if(server.FE[1]!=null && bool==1)
                {
                    agregaFES2();
                    agregaFES1();//agrega los Front End a los demas servidores
                    System.out.println("Agregue FE[1]");
                    bool++;
                }
                
                if(partidaNueva == 0 && server.jugandoPartida==false)
                {
                    System.out.println("Registrando una nueva partida S3");
                    partidaNueva=1;
                    server.jugandoPartida=true;
                    fecha = server.getFecha();//pone el mes/dia/año
                    server.fecha = server.getFecha();
                    hora_inicio = serverHora;
                    server.hora_Inicio = hora_inicio;//se guarda la hora de inicio en el servidor
                    jugandoPartidaS1(hora_inicio,fecha);//avisa que hay una partida en juego
                    jugandoPartidaS2(hora_inicio,fecha);
                    try 
                    {
                        System.out.println("fecha: "+fecha+" hora: "+hora_inicio);
                        QueryActual=BD.insertPartida(fecha, hora_inicio);
                    }catch (SQLException ex){
                        System.out.println("No se pudo hacer insertPartida");
                    }
                    QueryServer1();
                    QueryServer2();
                }

                if(server.peticion==true)//Revisa si hay una nueva peticion
                {
                    System.out.println("Tengo una peticion S3");
                    server.peticion = false;//como se acepta la peticion no se reciben en este momento
                    String nombreCarta = server.cartaActual;//obtiene la carta entregada al usuario
                    String clave = server.clave;//obtiene la clave de esa carta actual
                    if(!nombreCarta.equals(" "))//sino recibe cadena vacía
                    {    
                        System.out.println("nombreCarta: "+nombreCarta+" Clave: "+clave);
                        try 
                        {    
                            ImageIcon icon = IMAGEN.DisplayImage(clave);//se busca la imagen en la carpeta con el nombre "clave" correspondiente
                            imagenCarta.setIcon(icon);//pone la imagen en el label
                            QueryActual=BD.insertPeticion(clave, server.ipJugadorActual, server.valorCartaActual,serverHora,3); //inserta la peticion en la bd
                        } catch (IOException ex) {
                            System.out.println("Error: "+ex);
                            JOptionPane.showMessageDialog(null,"No se encontro la imagen"); 
                        } catch (SQLException ex) {
                            System.out.println("No se pudo hacer el insertPeticion");
                        }
                        QueryServer1();
                        QueryServer2();

                        if(reinicio==0)//si aun no se reinicia por primera vez
                        {
                            eliminaCartaS1(clave);
                            eliminaCartaS2(clave);
                        }//elimina la carta en el server 1
                    }else
                    {
                        JOptionPane.showMessageDialog(null,"Ingresa nombre de la cadena"); 
                    }    
                }
                System.out.println("isEmpty="+server.cartas.isEmpty()+" update:"+ejecuteUpdate+" server.primario="+server.primario);
                if(server.cartas.isEmpty()==true && ejecuteUpdate==false)//si ya no hay más elementos en la lista la partida termino
                {
                    System.out.println("Partida termino S3");
                    hora_fin = serverHora;//llamada a funcion que retorna la hora actual
                    try
                    {
                        System.out.println("Haciendo updatePartida en S3");
                        QueryActual=BD.updatePartida(hora_fin, server.hora_Inicio, server.fecha);//se manda la hora inicio del servidor que pudo se enviada remotamente para encontrar la hora de inicio correcta de la partida
                        System.out.println("QueryActual = "+QueryActual);
                    }catch(SQLException ex)
                    {
                        System.out.println("No se pudo hacer el updatePartida");
                    } 
                    QueryServer1();
                    QueryServer2();
                    ejecuteUpdate=true;
                }
            }
            
            try {
                Thread.sleep(500);
            } catch (Exception e) {
                System.out.println("no pudo esperar 500 milisegundos en h2: "+e);
            }
        }
        
        while(ct==h3)//hilo para la comparacion de consultas entre cada servidor
        {
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                System.out.println("excepcion esperando 8 segundos");
            }
            
            System.err.println("Verificando si el coordinador sigue en linea");
            System.err.println("El coordinador tiene ID="+server.id_coordinador);
            switch(server.id_coordinador)
            {
                case 1://si el coordinador es el server 1
                    try
                    {
                        server.servidor1Obj.online();//pregunta al server 1 si sigue vivo
                    }catch(RemoteException | NullPointerException e)
                    {
                        try 
                        {
                            if(server.servidor2Obj.comparaID(server.ID)==true)//hace la comparacion con el id del server 3
                            {
                                server.id_coordinador = server.ID;//si es mayor entonces server 2 sera el nuevo coordinador
                                server.primario = true;
                                server.servidor2Obj.soyCoordinador(server3Address, server.ID);
                                agregaFES2();
                                actualizaFE(0);
                                actualizaFE(1);
                            }
                        }catch (RemoteException | NullPointerException ex) {
                            server.id_coordinador = server.ID;
                            server.primario = true;
                            actualizaFE(0);
                            actualizaFE(1);
                        }
                    }
                    System.out.println("El coordinador tiene ID="+server.id_coordinador);
                break;
                
                case 2://si el coordinador es el server 2
                    try
                    {
                            server.servidor2Obj.online();//pregunta al server 1 si sigue vivo
                    }catch(RemoteException | NullPointerException e)
                    {
                            server.id_coordinador = server.ID;
                            server.primario = true;
                            actualizaFE(0);
                            actualizaFE(1);
                    }
                    System.out.println("El coordinador tiene ID="+server.id_coordinador);
                break;
                
                case 3:
                    try{
                        server.servidor1Obj.soyCoordinador(server1Address, server.ID);
                        server.servidor2Obj.soyCoordinador(server1Address, server.ID);
                        
                    }catch(RemoteException | NullPointerException e)
                    {
                        System.out.println("No se pudo actualizar coordinador en s2 y s3");
                    }finally
                    {
                        actualizaFE(0);
                        actualizaFE(1);
                    }
                break;
                
            }
            
            
        }
    }
}
