
import java.io.DataOutputStream;
//import java.net.Socket;
import java.net.*;
import java.util.Calendar;

public class MaestroXD extends javax.swing.JFrame implements Runnable {

    Calendar calendario;
    Thread hm;
    Relojes rm;
    
   
    int timer1 = 1000;

    /**
     * Creates new form Reloj
     */
    public MaestroXD() {
        rm = new Relojes(); //inicializando cada reloj por separado
        initComponents();

        hm = new Thread(this); //inicializando cada hilo       
        hm.start(); //ejecutando cada hilo
        setLocationRelativeTo(null);
        setTitle("Reloj");
        setVisible(true);
    }

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        while (ct == hm) //mientras el hilo se este ejecutando
        {
            if (rm.aux != 1) //si aun no entra por primera vez
            {
                rm.generaHora();
                //System.out.println("Acabo de ejecutar r1.calcula()");
                //System.out.println("hilo: "+h1.getName()+"Entre a calcular, auxiliar:"+r1.aux);
            }
            LabelRelojMaestro.setText(rm.hora + ":" + rm.minutos + ":" + rm.segundos);
            rm.actualiza();
            try {
                Thread.sleep(timer1);
            } catch (InterruptedException e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNModificarMIn = new javax.swing.JButton();
        LabelRelojMaestro = new javax.swing.JLabel();
        BTNModificarSec = new javax.swing.JButton();
        BTNModificarHora = new javax.swing.JButton();
        BTNModificarMIn1 = new javax.swing.JButton();
        BTNModificarMIn2 = new javax.swing.JButton();
        BTNModificarMIn3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNModificarMIn.setText("Enviar hora");
        BTNModificarMIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarMInActionPerformed(evt);
            }
        });

        LabelRelojMaestro.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        LabelRelojMaestro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelRelojMaestro.setText("lblReloj1");

        BTNModificarSec.setText("Modificar Segundo");
        BTNModificarSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarSecActionPerformed(evt);
            }
        });

        BTNModificarHora.setText("Modificar Hora");
        BTNModificarHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarHoraActionPerformed(evt);
            }
        });

        BTNModificarMIn1.setText("Modificar Minuto");
        BTNModificarMIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarMIn1ActionPerformed(evt);
            }
        });

        BTNModificarMIn2.setText("Enviar Segundo");
        BTNModificarMIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarMIn2ActionPerformed(evt);
            }
        });

        BTNModificarMIn3.setText("Enviar Minuto");
        BTNModificarMIn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarMIn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelRelojMaestro, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNModificarMIn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(BTNModificarMIn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(BTNModificarMIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BTNModificarHora, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(BTNModificarMIn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNModificarSec)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNModificarSec, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNModificarMIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNModificarHora, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelRelojMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNModificarMIn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNModificarMIn2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNModificarMIn3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNModificarMInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarMInActionPerformed
        // TODO add your handling code here:
        System.out.println("xdHour");
        try {
            Socket s = new Socket("192.168.1.72", 6677);//se conecta a la ip del cliente
            //Socket s = new Socket("192.168.1.82", 6667);
            DataOutputStream dout = new DataOutputStream(s.getOutputStream());
            String horaCompleta, horaEnviar;
            horaCompleta=LabelRelojMaestro.getText();
            System.out.println(""+horaCompleta);
            //horaCompleta = String.format("%02d", LabelRelojMaestro.);
            dout.writeUTF("" + horaCompleta);
            dout.flush();
            dout.close();
            s.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BTNModificarMInActionPerformed

    private void BTNModificarSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarSecActionPerformed
        hm.suspend();
        Modifica m = new Modifica(3);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        m.setTitle("Modificar Reloj 1");
        m.invocador = 3;
        m.relojOriginal = this;
        
    }//GEN-LAST:event_BTNModificarSecActionPerformed

    private void BTNModificarHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarHoraActionPerformed
        hm.suspend();
        Modifica m = new Modifica(1);
        m.invocador = 1;
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        m.setTitle("Modificar Reloj 1");

        m.relojOriginal = this;
    }//GEN-LAST:event_BTNModificarHoraActionPerformed

    private void BTNModificarMIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarMIn1ActionPerformed
        hm.suspend();
        Modifica m = new Modifica(2);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
        m.setTitle("Modificar Reloj 1");
        m.invocador = 2;
        m.relojOriginal = this;
    }//GEN-LAST:event_BTNModificarMIn1ActionPerformed

    private void BTNModificarMIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarMIn2ActionPerformed
        System.out.println("xdSEc");
        try {
            Socket s = new Socket("192.168.1.72", 6679);
            //Socket s = new Socket("192.168.1.82", 6667);
            DataOutputStream dout = new DataOutputStream(s.getOutputStream());
            String segundoCompleta, segundoEnviar;
            segundoCompleta=LabelRelojMaestro.getText();
            System.out.println(""+segundoCompleta);
            //horaCompleta = String.format("%02d", LabelRelojMaestro.);
            dout.writeUTF("" + segundoCompleta);
            dout.flush();
            dout.close();
            s.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BTNModificarMIn2ActionPerformed

    private void BTNModificarMIn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarMIn3ActionPerformed
        System.out.println("xdMin");
        try {
            Socket s = new Socket("192.168.1.72", 6678);
            //Socket s = new Socket("192.168.1.82", 6667);
            DataOutputStream dout = new DataOutputStream(s.getOutputStream());
            String minutoCompleta, minutoEnviar;
            minutoCompleta=LabelRelojMaestro.getText();
            System.out.println(""+minutoCompleta);
            //horaCompleta = String.format("%02d", LabelRelojMaestro.);
            dout.writeUTF("" + minutoCompleta);
            dout.flush();
            dout.close();
            s.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BTNModificarMIn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNModificarHora;
    private javax.swing.JButton BTNModificarMIn;
    private javax.swing.JButton BTNModificarMIn1;
    private javax.swing.JButton BTNModificarMIn2;
    private javax.swing.JButton BTNModificarMIn3;
    private javax.swing.JButton BTNModificarSec;
    private javax.swing.JLabel LabelRelojMaestro;
    // End of variables declaration//GEN-END:variables
}
